---
title: "Final project"
author: "Vishal Sinha (vishal.sinha@helsinki.fi)"
date: "3/05/2017"
output: html_document
---

```{r global_options, include=TRUE}
knitr::opts_chunk$set(fig.width=8, fig.height=8, warning=FALSE, message=FALSE)
```


```{r}
### Load all the libraries required for the analysis
library(ggplot2)
library("GGally")
library(corrplot)
library(dplyr)
library(factoextra)
library(FactoMineR)
```

```{r}
### Read the cor data
data_cor = read.table("/Users/vsinha/IODS-final/corr_final_data", header = T)
### Explore the cor data
dim(data_cor)
str(data_cor)
summary(data_cor)
```

```{r}
### Read the pca data
data_pca = read.table("/Users/vsinha/IODS-final/pca_data", header = T)
### Explore the pca data
dim(data_pca)
str(data_pca)
summary(data_pca)
```

```{r}
### Plot all variables against each other
ggpairs(data_cor) + ggtitle("All variables against each other")
### Plot the correlation matrix
cor_matrix = cor(data_cor) 
corrplot(cor_matrix, method="circle", type = "upper", cl.pos = "r", tl.pos = "d", tl.cex = 0.5, addCoef.col = "black")
```

```{r}
scale_data=scale(data_pca)
pca = prcomp(scale_data)
pca
summary(pca)
biplot(pca, choices = 1:2, cex = c(0.7, 1), col = c("grey40", "deeppink2"))
eigenvalues <- get_eigenvalue(pca)
head(round(eigenvalues, 2))
fviz_screeplot(pca)
```
